name: CI Build and Test

on: 
  push:
    branches: 
    - dev
    - master
    paths:
    - sources/**
    - .github/**
  pull_request:
    branches: 
    - master
    - dev
    paths:
    - sources/**

jobs:
  Font-ci-job:
    runs-on: ubuntu-latest
    name: CI Static ttf
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        # The --pre flag below will ensure we use the latest Font Bakery pre-releases
        # and benefit from its newest checks:
        run: |
          sudo apt install libharfbuzz-dev libharfbuzz-bin libglib2.0-dev libcairo2-dev
          python -m pip install --upgrade pip
          pip install freetype-py
          pip install --pre fontbakery
          pip install gftools
      - name: Install ttfautohint
        run: |
          sudo apt-get update
          sudo apt-get install ttfautohint
      - name: Build fonts
        id: build_fonts
        run: gftools builder sources/config.yml
      - name: Upload Fonts
        uses: actions/upload-artifact@v3
        with:
          name: Praise-Font
          path: fonts/
      - name: Make Fontbakery Report
        uses: f-actions/font-bakery@v2
        with:
          version: "latest"
          subcmd: "check-googlefonts"
          args: "-C --succinct --loglevel WARN --ghm fonts/report.md"
          path: "fonts/ttf/*.ttf"